AutenticacaoDotNet/Models/Credencial.cs
using System.ComponentModel.DataAnnotations;

namespace AutenticacaoDotNet.Models
{
    public class Credencial
    {
        [Required]
        [Display(Name = "User Name")]
        public string UserName { get; set; } = string.Empty;

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; } = string.Empty;

        [Display(Name = "Remember Me")]
        public bool RememberMe { get; set; }

    }
}

AutenticacaoDotNet/Models/ErrorViewModel.cs
namespace AutenticacaoDotNet.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AutenticacaoDotNet/Controllers/AccountController.cs
using AutenticacaoDotNet.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Formatters;
using System.Net;
using System.Security.Claims;

namespace AutenticacaoDotNet.Controllers
{
    public class AccountController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AccessDenied()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

        public IActionResult Login()
        {
            return View(new Credencial());
        }

        [HttpPost]
        public async Task<IActionResult> Login(Credencial credencial)
        {

            if (!ModelState.IsValid)
                return View();

            if (credencial.UserName == "admin" && credencial.Password == "123456")
            {
                // Creating the security context
                var claims = new List<Claim> {
                    new Claim(ClaimTypes.Name, "admin"),
                    new Claim(ClaimTypes.Email, "admin@mywebsite.com"),
                   // new Claim("RH", "RH"),
                    new Claim("ManutencaoPredial", "true"),
                    new Claim("Holerite", "true"),
                    new Claim("EmploymentDate", "2025-01-01"),
                    //new Claim(ClaimTypes.Role, "RH"),
                    //new Claim(ClaimTypes.Role, "Admin1")
                };
                var acessos = BaseBancoMock.Dados.RetornaAcessos();

                foreach (var acesso in acessos)
                {
                   claims.Add(new Claim(ClaimTypes.Role, acesso));
                }

                var identity = new ClaimsIdentity(claims, "MeuCookieAuthenticacao");
                ClaimsPrincipal claimsPrincipal = new ClaimsPrincipal(identity);

                var authProperties = new AuthenticationProperties
                {
                    IsPersistent = credencial.RememberMe
                };

                await HttpContext.SignInAsync("MeuCookieAuthenticacao", claimsPrincipal, authProperties);

                return RedirectToAction("Index", "Home");

            }
            return Json("Ok");
        }
    }
}

AutenticacaoDotNet/Controllers/AdministrativoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AutenticacaoDotNet.Controllers
{
    [Authorize(Policy = "Admin1")]
    public class AdministrativoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AutenticacaoDotNet/Controllers/HomeController.cs
using System.Diagnostics;
using AutenticacaoDotNet.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AutenticacaoDotNet.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AutenticacaoDotNet/Controllers/RHController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AutenticacaoDotNet.Controllers
{
    [Authorize(Policy = "RH")]
    public class RHController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AutenticacaoDotNet/Views/Administrativo/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome Admin</h1>

</div>

AutenticacaoDotNet/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AutenticacaoDotNet/Views/RH/Index.cshtml
<div class="text-center">
    <h1 class="display-4">Welcome RH </h1>

</div>

AutenticacaoDotNet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AutenticacaoDotNet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AutenticacaoDotNet.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AutenticacaoDotNet</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RH" asp-action="Index">RH</a>
                        </li>
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Administrativo" asp-action="Index">Administrativo</a>
                        </li>
                    </ul>
                </div>
                <div class="mr-2">
                    <partial name="_LoginStatusPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - AutenticacaoDotNet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AutenticacaoDotNet/Views/Shared/_LoginStatusPartial.cshtml
@if (User is not null && User.Identity is not null && User.Identity.IsAuthenticated)
{
    <form method="post" asp-controller="Account" asp-action="Logout" class="form-inline">
        Welcome @User.Identity.Name
        <button type="submit" class="ml-2 btn btn-link">Logout</button>
    </form>

}
else
{
    <a class="btn btn-link" asp-page="/Account/Login">Login</a>
}